Add docker image for compiler-course
NN-complr-tech/Docker pull request #4
Opened 2024-12-30 14:35 UTC by Kuznetsov-Artyom

2024-12-31 21:09 UTC, aobolensk requested changes

2024-12-31 21:09 UTC, aobolensk commented on compiler-course/README.md
> +- linux/arm64 - ARM
What is the difference here?

2025-01-01 00:51 UTC, Kuznetsov-Artyom commented on compiler-course/README.md
> +- linux/arm64 - ARM
From a technical point of view - there is no difference, but for clarity I will leave arm64

2025-01-01 18:47 UTC, aobolensk approved these changes

2025-01-01 18:49 UTC, merged